### ISSUE TITLE
add feature toggle to allow temporary disabling of workflows

### ISSUE THREAD

**Issue by ksatirli** [workloads/github-organization#7]
In some cases, it might be desirable to disable a workflow, based on a feature toggle (= GHA Organizational Variable)

The code for this is along the lines of:

```yaml
jobs:
    verify:
    name: verify
    if: ${{ vars.ENABLE_WORKFLOWS == 'true' }}
    runs-on: ubuntu-latest
```
